### ISSUE TITLE
ADGroup query in Deploy_WEC.ps1

### ISSUE THREAD

**Issue by atiedemann** [mczerniawski/WEFTools#13]
Hello Mateusz,

yesterday I test your module and deploy a WEC Server. In your code where you check the Active Directory groups, I get an error because of existing group. Your code will create a group that already exist, because you test with variable $sampleRuleName and you lose the prefix name of the group.
============ your code ============
```powershell
foreach ($sampleRuleName in $GroupNames){
    $groupProps = @{
        Name = '{0}-{1}' -f $GroupPrefix ,$sampleRuleName
        Path = $OUPathforWEFGroups
        GroupScope = 'Universal'
        Description= 'Computers from this group will receive subscription {0} from WEC server' -f $sampleRuleName
    }
    $testGroup = Get-ADGroup -filter {Name -eq $sampleRuleName} -ErrorAction SilentlyContinue
    if (-not ($testGroup)) {
        Write-Host "Creating Group {$($groupProps.Name)}"
        New-ADGroup @groupProps
    }
}
```
I changed the code with a try catch block and wit that I get all groups in Active directory and if a group is already there I get no error.
Please test this and if you want update your code. :-)
============ my code ============

```powershell
foreach ($sampleRuleName in $GroupNames){
    $groupProps = @{
        Name = '{0}-{1}' -f $GroupPrefix ,$sampleRuleName
        Path = $OUPathforWEFGroups
        GroupScope = 'Universal'
        Description= 'Computers from this group will receive subscription {0} from WEC server' -f $sampleRuleName
    }

    try {
        $null = Get-ADGroup -Identity ('{0}-{1}' -f $GroupPrefix ,$sampleRuleName) -ErrorAction Stop
    } catch {
        Write-Host "Creating Group {$($groupProps.Name)}"
        New-ADGroup @groupProps
    }
}
```

Thanks and have a nice day
Arne

**Comment by mczerniawski** [comment]
I'll have to check it cause within this part
```powershell
$GroupNames = Get-ChildItem $DestinationFullPath -Filter '*.xml' | Select-Object -ExpandProperty BaseName
foreach ($sampleRuleName in $GroupNames){
    $groupProps = @{
        Name = '{0}-{1}' -f $GroupPrefix ,$sampleRuleName
        Path = $OUPathforWEFGroups
        GroupScope = 'Universal'
        Description= 'Computers from this group will receive subscription {0} from WEC server' -f $sampleRuleName
    }
    $testGroup = Get-ADGroup -filter {Name -eq $sampleRuleName} -ErrorAction SilentlyContinue
    if (-not ($testGroup)) {
        Write-Host "Creating Group {$($groupProps.Name)}"
        New-ADGroup @groupProps
    }
}
```
there's the test for given grouop and if not existing it will (if block) create the group
```powershell
 $testGroup = Get-ADGroup -filter {Name -eq $sampleRuleName} -ErrorAction SilentlyContinue
    if (-not ($testGroup)) {
```

but I will definitely check this out

**Comment by PrzemyslawKlys** [comment]
I think that using try/catch is not optimal in this scenario. Implementation by @mczerniawski  seems to be easier on the eyes. If group doesn't exists Error Action SilentlyContinue will return $null for $TestGroup. We then simply do

```
if (-not $testGroup)  {
    New-ADGroup 
}
```

(You don't need a double bracket for that @mczerniawski ). Having try/catch doesn't add anything. Or am I missing something @atiedemann?

**Comment by atiedemann** [comment]
I think the main problem was that you ask for a group with "-eq $sampleRuleName" and create a group with name $groupProps.Name.
In my environment not all groups are created with the code. After I change the code I get no error and alle groups are created.

@mczerniawski : Please check the code with try catch and let me know if it is working.
@PrzemyslawKlys : You are right with the double bracket

**Comment by mczerniawski** [comment]
Yes, you are right, I'm looking for a groupname (like 'Account-Lockout') andthen create WEF-Account-Lockout if WEF was the prefix.
Fixing that with 8fedb3d
